# SPDX-FileCopyrightText: 2020 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/yaml-lint.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/json-validation.yml
      - /gitlab-templates/cppcheck.yml
      - /gitlab-templates/snap-snapcraft-lxd.yml
