language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
  - sudo apt-get update -qq
    
install: 
  - sudo apt-get -y install libxml2-utils qt59base qt59svg qt59declarative qt59quickcontrols qt59graphicaleffects qt59multimedia qt59svg qt59xmlpatterns qt59tools qt59translations qt59sensors
  - source /opt/qt*/bin/qt*-env.sh

script:
  - git submodule init && git submodule update
  - mkdir build ; cd build/ # CMakeLists.txt:90 says that building in the source directory is not supported
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make getSvnTranslations
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - make BuildTranslations
  - make -j$(nproc)
  - make DESTDIR=appdir install ; find appdir/
  - mkdir -p appdir/usr/share/applications/ ; cp ../org.kde.gcompris.desktop appdir/usr/share/applications/ # FIXME: The step before should have done that
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ ; cp ../images/256-apps-gcompris-qt.png appdir/usr/share/icons/hicolor/256x256/apps/gcompris-qt.png # FIXME: This as well
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=../..
  - cp /opt/qt*/plugins/imageformats/libqsvg.so ./appdir/usr/plugins/imageformats/ # Workaround until https://github.com/probonopd/linuxdeployqt/issues/82 is implemented
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=../..

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./GCompris*.AppImage https://transfer.sh/GCompris-git.$(git rev-parse --short HEAD)-x86_64.AppImage
